name: Mobile App Name
description: A super tagline for the mobile app
full_description: 'A more complete description of the mobile app<br>
<br>With a lot of features:
<br>- Feature 1
<br>- Feature 2
<br>- Feature 3'
android: abdul-jaleel-al-fahim-school.web.app
iOS: abdul-jaleel-al-fahim-school.web.app
web: abdul-jaleel-al-fahim-school.web.app